### ISSUE TITLE
google style API has changed

### ISSUE THREAD

**Issue by nhooyr** [lestrrat-go/slack#61]
https://github.com/google/google-api-go-client/blob/0e8d13b5c025da6a7cf249bb854e5869921dd459/GettingStarted.md#using-the-service

There is no single client now. Just services and sub services where the sub services are fields.

**Comment by lestrrat** [comment]
oh bummer

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.
